version: '3.9'


services:

  database:
    container_name: dasa-challenge-database
    image: postgres:14.1-alpine
    hostname: postgres
    environment:
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: dasa-challenge-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "9229:9229"
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
